<a href="https://colab.research.google.com/github/AndresVelez31/AlgebraLineal/blob/main/Gu%C3%ADa_de_Python_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Guía #2: Álgebra de Matrices**

**Objetivo:** Usar el lenguaje de programación de Python para el desarrollo y apropiación de las propiedades básicas de las matrices.

**Temas:** En esta guía se trabajarán las distintas  operaciones entre matrices como: suma, resta, multiplicación por escalar y multiplicación entre matrices; y transpuesta de una matriz.




## **Creación de matrices**

Para la creación y tratado de matrices se debe llamar la biblioteca "**numpy**". Ésta biblioteca da soporte para crear vectores y matrices, y permite la realización de las diversas operaciones entre éstos elementos. "**Numpy**" generalmente se importa con el alias "**np**". En los siguientes ejemplos se muestra cómo llamar esta biblioteca.

### **Ejemplo 1:**
Crear las siguientes matrices:



\begin{equation*}
 A =
\begin{pmatrix}
1 & 2 & 3\\
-1 & 4 & 0\\
-6 & 0 & 10
\end{pmatrix},
 \hspace{1cm}
B =
\begin{pmatrix}
2 & 5 & 0\\
7 & 3 & 8\\
3 & 0 & 1
\end{pmatrix},
\hspace{1cm}
C =
\begin{pmatrix}
5 & -8 & 0\\
2 & -4 & -3 \\
-5 & 0 & 4
\end{pmatrix},
\hspace{1cm}
I =
\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}.
\end{equation*}


In [ ]:
# Solución del Ejemplo 1.

# Importamos la biblioteca numpy con el alias np.
import numpy as np

# Creación de las matrices A, B, C y I.

A = np.array([[1, 2, 3], [-1, 4, 0], [-6, 0, 10]])

B = np.array([[2, 5, 0], [7, 3, 8], [3, 0, 1]])

C = np.array([[5, -8, 0], [2, -4, -3], [-5, 0, 4]])

# Podemos crear la matriz identidad I como se hizo con la matrices anteriores, o simplemente usar el comando np.eye

I = np.eye(3) # matriz identidad 3 x 3

# Imprimo los matrices

print('A =', A), print('B =', B), print('C =', C), print('I =', I);

A = [[ 1  2  3]
 [-1  4  0]
 [-6  0 10]]
B = [[2 5 0]
 [7 3 8]
 [3 0 1]]
C = [[ 5 -8  0]
 [ 2 -4 -3]
 [-5  0  4]]
I = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## **Suma, resta y producto por escalar**

### **Ejemplo 2:**
Use las matrices establecidas en el Ejemplo 1 para realizar las operaciones indicadas:



a).   $(A + 5B)-(3I-2C).$

b).   $-5B + (194A - 80C) - 0.56I .$

c). $ -165(A - B + 8C - I) + \frac{4}{9}C + A     .$





In [ ]:
# Solución del Ejemplo 2.

# a). Operación Z = (A + 5B)-(3I-2C)

Z = (A + 5*B)-(3*I-2*C)

# Imprimo la matriz Z

print('Z =', Z);

Z = [[18. 11.  3.]
 [38.  8. 34.]
 [-1.  0. 20.]]


In [ ]:
# b). Operación Z = -5B + (194A-80C) - 0.56I

Z = -5*B + (194*A-80*C) - 0.56*I

# Imprimo la matriz Z

print('Z =', Z);

Z = [[-216.56 1003.    582.  ]
 [-389.   1080.44  200.  ]
 [-779.      0.   1614.44]]


In [ ]:
# c). Operación Z = -165(A - B + 8C - I) + (4/9)C + A

Z = -165*(A - B + 8*C - I) + (4/9)*C + A

# Imprimo la matriz Z

print('Z =', Z);

Z = [[-6266.77777778 11053.44444444  -492.        ]
 [-1320.11111111  5282.22222222  5278.66666667]
 [ 8076.77777778     0.         -6588.22222222]]


## **Multiplicación entre matrices**

### **Ejemplo 3:**
Crear las siguientes matrices

\begin{equation*}
 A =
\begin{pmatrix}
3 & -2 & 3 & 45 & -8 & 0\\
7 & 5 & -1 & 97 & -145 & 123\\
-2 & 94 & 500 & 1 & 3 & 7 \\
8 & 2 & 8 & 1 & 2 & -12 \\
\end{pmatrix},
 \hspace{1cm}
B =
\begin{pmatrix}
22 & 25 & 0 & 6\\
-7 & 2 & 56 & -10\\
3 & 0 & 1 & 87
\end{pmatrix},
\hspace{1cm}
C =
\begin{pmatrix}
-5 & 8 & 0 & 1\\
-2 & 4 & 3 & 2\\
5 & 0 & -4 & 0 \\
-5 & 0 & 4 & 3
\end{pmatrix},
\hspace{1cm}
I =
\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}.
\end{equation*}


y realizar las operaciones indicadas:


a).   $7BA.$

b).   $IA.$

c). $IC-CI.$

d). $(40C + 20I)A - 9A$



In [ ]:
# Solución del Ejemplo 3.

# Creación de las matrices A, B, C y I.

A = np.array([[3, -2, 3, 45, -8, 0], [7, 5, -1, 97, -145, 123], [-2, 94, 500, 1, 3, 7],[8, 2, 8, 1, 2, -12]])

B = np.array([[22, 25, 0, 6], [-7, 2, 56, -10], [3, 0, 1, 87]])

C = np.array([[-5, 8, 0, 1], [-2, 4, 3, 2], [5, 0, -4, 0],[-5, 0, 4, 3]])

# Podemos crear la matriz identidad I como se hizo con la matrices anteriores, o simplemente usar el comando np.eye

I = np.eye(4) # matriz identidad 4 x 4

# Visualización de las matrices

print('A =', A), print('B =', B), print('C =', C), print('I =', I);

A = [[   3   -2    3   45   -8    0]
 [   7    5   -1   97 -145  123]
 [  -2   94  500    1    3    7]
 [   8    2    8    1    2  -12]]
B = [[ 22  25   0   6]
 [ -7   2  56 -10]
 [  3   0   1  87]]
C = [[-5  8  0  1]
 [-2  4  3  2]
 [ 5  0 -4  0]
 [-5  0  4  3]]
I = [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# a). Operación Z = 7BA

# Nota: El producto entre matrices se ejecuta con el comando @

Z = 7*B@A

print('Z =', Z);

Z = [[  2023    651    623  23947 -26523  21021]
 [ -1393  36876 195279   -525   -602   5306]
 [  4921   1834   8435   1561   1071  -7259]]


In [ ]:
# b). Operación Z = IA

Z = I@A

print('Z =', Z);

Z = [[   3.   -2.    3.   45.   -8.    0.]
 [   7.    5.   -1.   97. -145.  123.]
 [  -2.   94.  500.    1.    3.    7.]
 [   8.    2.    8.    1.    2.  -12.]]


In [ ]:
# c). Operación Z = IC - CI

Z = I@C - C@I

print('Z =', Z);

Z = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# d). Operación Z = (40C + 20I)A - 9A

Z = (40*C + 20*I)@A - 9*A

print('Z =', Z);

Z = [[  1993.   2058.   -567.  22575. -44808.  38880.]
 [  1357.  12455.  60229.  13187. -23635.  20913.]
 [   898. -14406. -73900.   8851.  -2047.  -1043.]
 [   128.  15702.  80448.  -8709.   2342.   -452.]]


## **Transpuesta de una matriz**

### **Ejemplo 4:**
Crear las siguientes matrices

\begin{equation*}
 A =
\begin{pmatrix}
18 & -7 \\
4 & 9 \\
0 & 1 \\
-200 & 15\\
-321 & 973 \\
4 & -36 \\
8 & 20
\end{pmatrix},
 \hspace{1cm}
B =
\begin{pmatrix}
-5 & 0 & 0 & -4 & 6 & 1\\
4 & 1 & 1 & 30 & -43 & 2
\end{pmatrix},
\end{equation*}

y realizar las operaciones indicadas:

a). $ A^{T}.$

b). $ B^{T}.$

c). $(3A)^{T}.$

d). $(AB)^T$

In [ ]:
# Solución del Ejemplo 4.

# Creo las matrices A y B

A = np.array([[18, -7], [4, 9], [0, 1],[-200, 15],[-321, 973],[4, -36],[8, 20]])

B = np.array([[-5, 0, 0, -4, 6, 1], [4, 1, 1, 30, -43, 2]])

# Visualización de A y B

print('A =', A), print('B =', B);

A = [[  18   -7]
 [   4    9]
 [   0    1]
 [-200   15]
 [-321  973]
 [   4  -36]
 [   8   20]]
B = [[ -5   0   0  -4   6   1]
 [  4   1   1  30 -43   2]]


In [ ]:
# a). Operación Z = A^T

# Nota: La transpuesta de una matriz se puede ejecutar con el comando np.transpose

Z = np.transpose(A)

print('Z =', Z);

Z = [[  18    4    0 -200 -321    4    8]
 [  -7    9    1   15  973  -36   20]]


In [ ]:
# b). Operación Z = B^T

Z = np.transpose(B)

print('Z =', Z);

Z = [[ -5   4]
 [  0   1]
 [  0   1]
 [ -4  30]
 [  6 -43]
 [  1   2]]


In [ ]:
# c). Operación Z = (3A)^T

Z = np.transpose(3*A)

print('Z =', Z);

Z = [[  54   12    0 -600 -963   12   24]
 [ -21   27    3   45 2919 -108   60]]


In [ ]:
# d). Operación Z = (AB)^T

Z = np.transpose(A@B)

print('Z =', Z);

Z = [[  -118     16      4   1060   5497   -164     40]
 [    -7      9      1     15    973    -36     20]
 [    -7      9      1     15    973    -36     20]
 [  -282    254     30   1250  30474  -1096    568]
 [   409   -363    -43  -1845 -43765   1572   -812]
 [     4     22      2   -170   1625    -68     48]]



### **Ejemplo 5:**
Determine cuáles de las igualdades dadas a continuación son ciertas para las siguientes matrices:


\begin{equation*}
 A =
\begin{pmatrix}
4 & -7 & -1 & 3 \\
4 & 9 & 5 & 0 \\
1 & -1 & 6 & 10 \\
8 & 5 & -5 & 2
\end{pmatrix},
 \hspace{1cm}
B =
\begin{pmatrix}
-5 & 3 & 4 & -4\\
-3 & 78 & 9 & -2\\
-4 & 6 & 1 & -3\\
2 & 4 & 0 & 12
\end{pmatrix},
\hspace{1cm}
C =
\begin{pmatrix}
3 & 1 & 1 & 1\\
0 & 0 & -4 & 2\\
0 & 2 & 3 & 3\\
2 & 7 & 1 & 2
\end{pmatrix}.
\end{equation*}

a). $ AB = BA.$

b). $ (A^{T})^T = A.$

c). $(AB)^{T} = A^T B^T.$

d). $(C+C^T)B^T = (BC^T)^T + (BC)^T$




In [ ]:
# Solución del Ejemplo 5.

# Creo las matrices A, B y C

A = np.array([[4, -7, -1, 3], [4, 9, 5, 0], [1, -1, 6, 10],[8, 5, -5, 2]])

B = np.array([[-5, 3, 4, -4], [-3, 78, 9, -2], [-4, 6, 1, -3],[2, 4, 0, 12]])

C = np.array([[3, 1, 1, 1], [0, 0, -4, 2], [0, 2, 3, 3],[2, 7, 1, 2]])


In [ ]:
# a). AB = BA

# Hallo las matrices Z =  AB y W = BA

Z = A@B

W = B@A

print('Z =', Z), print('W =', W);

Z = [[  11 -528  -48   37]
 [ -67  744  102  -49]
 [  -6    1    1  100]
 [ -31  392   72   -3]]
W = [[-36  38  64  17]
 [293 704 457  77]
 [-15  66  55  -8]
 [120  82 -42  30]]


Observamos que el producto $AB$ genera una matriz diferente al producto $BA$, por lo tanto, el producto de matrices **no es conmutativo**.

In [ ]:
# b). (A^T)^T = A

# Hallo la matriz  Z = (A^T)^T

Z = np.transpose(np.transpose(A))

print('Z =', Z), print('A =', A);

Z = [[ 4 -7 -1  3]
 [ 4  9  5  0]
 [ 1 -1  6 10]
 [ 8  5 -5  2]]
A = [[ 4 -7 -1  3]
 [ 4  9  5  0]
 [ 1 -1  6 10]
 [ 8  5 -5  2]]


Del cálculo anterior, podemos ver que la igualdad se satisface, es decir, que $(A^T)^T = A$. En efecto, dicha igualdad es válida para cualquier matriz.

In [ ]:
# c). (AB)^T = (A^T)(B^T)

# Calculo las matrices Z = (AB)^T y W = (A^T)(B^T)

Z = np.transpose(A@B)

W = np.transpose(A)@np.transpose(B)

print('Z =', Z), print('W =', W);

Z = [[  11  -67   -6  -31]
 [-528  744    1  392]
 [ -48  102    1   72]
 [  37  -49  100   -3]]
W = [[-36 293 -15 120]
 [ 38 704  66  82]
 [ 64 457  55 -42]
 [ 17  77  -8  30]]


Los resultados indican que tal igualdad no es cierta para estas matrices. Por ello, en general se que $(AB)^{T} \not = A^T B^T.$

In [ ]:
# d). (C + C^T)(B^T) = (BC^T)^T + (BC)^T

# Hallo las matrices Z =  (C + C^T)(B^T) y W = (BC^T)^T + (BC)^T

Z = (C + np.transpose(C))@np.transpose(B)

W = np.transpose(B@np.transpose(C)) + np.transpose(B@C)

print('Z =', Z), print('W =', W);

Z = [[ -35   63  -26   52]
 [ -49  -39  -33  110]
 [  -3 -113  -22   42]
 [  12  721   34   90]]
W = [[ -35   63  -26   52]
 [ -49  -39  -33  110]
 [  -3 -113  -22   42]
 [  12  721   34   90]]


En consecuencia, la propiedad se satisface para dichas matrices. En general, esta propiedad es cierta para cualquier par de matrices.

# **Problemas de práctica**

**Ejercicio 1:** Defina las siguientes matrices

\begin{equation*}
 A =
\begin{pmatrix}
4 & -6 & 50 & -8 & 1 & 0 & 33 7 & 2\\
-7 & 0 & -66 & 1 & 4 & 0 & 2 & 4
\end{pmatrix},
 \hspace{0.7cm}
B =
\begin{pmatrix}
-5 & 2 \\
40 & -1 \\
0 & 4
\end{pmatrix},
\hspace{0.7cm}
C =
\begin{pmatrix}
3 & 8 & 45 & 21 & 10 & -9 & -2 & 2 \\
-5 & 5 & -54 & 6 & 7 & -245 & 1 & 4
\end{pmatrix}.
\end{equation*}

In [ ]:
# Empiece aquí su código



**Ejercicio 2:** Usando las matrices anteriormente definidas, realice las operaciones indicadas:

a). $-6A + 3C.$

b). $ A + 2B.$ Debería obtener un error, explique la causa del error.

c). $(BC)^{T}$.

d). $CB$. Explique el resultado obtenido.

e). $AC^T$ y $C^TA$. ¿Coinciden los resultados?

f). $(A - C)^{T}$ y $A^T - C^T.$ ¿Coinciden los resultados?

g). $\|\vec{u}\|A + (\vec{u}\cdot \vec{v})C,$ donde $\vec{u} = (1, 0, 56)$ y $\vec{v} = (-30, 6, 8).$


In [ ]:
# Empiece aquí su código

 # a).


In [ ]:
# b).

In [ ]:
# c).

In [ ]:
# d).

In [ ]:
# e).

In [ ]:
# f).

In [ ]:
# g).