<a href="https://colab.research.google.com/github/AndresVelez31/AlgebraLineal/blob/main/Laboratorio_2025_Version_6_Done.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#**Laboratorio (6%)**

**Instrucciones:** El presente trabajo consta de seis (6) problemas cada uno con un valor asignado. El profesor del curso es el encargado de calificar el trabajo, y para ello tendrá en cuenta el  procedimiento realizado (que debe mostrar el estudiante) y las respectivas respuestas a los ejercicios. Por favor, **comentar de forma organizada y coherente** los pasos realizados.


 El laboratorio **debe ser realizado en grupos, con el número máximo integrantes definido por el profesor**. Se debe entregar un solo documento por grupo, y dentro del mismo **debe aparecer de forma clara el nombre completo de todos los integrantes**.  Ver espacio a continuación.


**Formato de entrega:** Para la entrega de este trabajo, descargue el archivo en **formato PDF** (esto lo consigue con la combinación de teclas **ctrl + p** y guardando el archivo en el formato requerido) y enviarlo a través de Interactiva en el buzón designado para ello.

**NOTA:** Revisar el documento antes de enviarlo. Asegúrese de que el documento sea legible y tenga todos los procedimientos con las respuestas impresas de los cálculos realizados.

In [ ]:
########---------------Nombre completo de los integrantes del grupo de trabajo-------------------##########

# Integrante 1: Emily Cardona Castañeda

# Integrante 2: Thomas Gonzalez Velez



### **Ejercicio #1: (0.8)**
Dados los siguientes vectores

\begin{equation*}
 \vec{u} = (20, 15, 1),
 \hspace{0.5cm}
 \vec{v} = (18, -1, 30),
\hspace{0.5cm}
 \vec{w} = (30, -6, 71),
 \hspace{0.5cm}
 \vec{z} = (13, -4, 28),
\end{equation*}

realizar las operaciones indicadas:

a). **(0.2)** $ (\vec{u} + \vec{z}- \vec{v}) \cdot (\vec{z}-3\vec{w} + \vec{v}).$

b). **(0.2)** $\| \vec{z}- \vec{w}\|- \|\vec{w} \times \vec{u}\|.$

c). **(0.2)** $\|\vec{u}\|(\vec{v} + \vec{z}) + \| 2\vec{z}- 3\vec{w}\|\vec{z}.$

d). **(0.2)** Hallar dos vectores $\vec{p}$ y $\vec{h}$ tales que $\vec{v} = \vec{p} + \vec{h}$ con $\vec{p}$ paralelo a $\vec{u}$ y $\vec{h}$ ortogonal a $\vec{u}$.

In [ ]:
# Solución Ejercicio 1. (No olvide imprimir las respuestas de sus cálculos)

# Importar la bibliotecas numpy con el alias np y math.
import numpy as np
import math


import numpy as np

# Vectores dados
u = np.array([20, 15, 1])
v = np.array([18, -1, 30])
w = np.array([30, -6, 71])
z = np.array([13, -4, 28])

# a)
a_vec1 = u + z - v
a_vec2 = z - 3 * w + v
a = np.dot(a_vec1, a_vec2)
print("a) Resultado:", a)

# b)
b_norm1 = np.linalg.norm(z - w)
b_cross = np.cross(w, u)
b_norm2 = np.linalg.norm(b_cross)
b = b_norm1 - b_norm2
print("b) Resultado:", b)

# c)
c_term1 = np.linalg.norm(u) * (v + z)
c_term2 = np.linalg.norm(2 * z - 3 * w) * z
c = c_term1 + c_term2
print("c) Resultado:", c)

# d)
lambda_proj = np.dot(v, u) / np.dot(u, u)
p = lambda_proj * u
h = v - p
print("d) Vector p (paralelo a u):", p)
print("d) Vector h (ortogonal a u):", h)



a) Resultado: -574
b) Resultado: -1798.7225901766406
c) Resultado: [2983.51580953 -804.45259306 6206.62796756]
d) Vector p (paralelo a u): [11.98083067  8.985623    0.59904153]
d) Vector h (ortogonal a u): [ 6.01916933 -9.985623   29.40095847]


### **Ejercicio #2. (1.2)**
Ana ha decidido enviarle un mensaje codificado a Pedro a través del **método Hill**. El mensaje codificado es:

0, -7, 8, 23, -15, 0, -16, -23, -3, 14, -16, -3, 23, 11, 13, -15, 7, 2, -11, -15, 1,   15, 0, 5, 92, 51, 160, -1, 129, 90, 50, 97, 25, 52, 152, 13, 107, 11, 83, 183, 87, 84, 141, 109, 67, 105, 54, 99, 124, 59, 144, 43, 113, 54, 30, 105, 7,  100, 166, -11, 155, 37, 87, 191, 105, 88, 119, 111, 53, 143, 72, 95, -68, -42, -112,  -10, -82, -52, -8, -72, 34, -58, -126, 46, -122, -12, -56, -166, -56, -48, -98, -70,  -44, -118, -16, -48, 68, 49, 104, -7, 97, 62, 38, 79, 23, 24, 98, 11, 51, 1, 55, 127,   45, 66, 85, 83, 49, 65, 28, 67


Para el proceso de codificacion, Ana tuvo presente la siguiente información:

1. Llave de codificación: 0, 0, 1, -1, 0, 0, 4, -1, 1, 2, -2, 4, 1, 1, 2, 2, -4, 0, 0, -2, 0, 2, -1, 1, 2.
2. Dimensión de la matriz de codificación $5 \times 5$.

a). **(0.4)** Cree e imprima la matriz de codificación $A$, y la matriz codificada $C$.

b). **(0.4)** Cree e imprima la matriz plana $B$ (matriz que contiene el mensaje que se desea codificar).

c). **(0.4)** ¿Cuál es el mensaje que le envío Ana a Pedro?


**NOTA:** Remitirse a la **Guía # 3** en la cual se explica el Método Hill.

In [ ]:
import numpy as np


mensaje_codificado = [
    0, -7, 8, 23, -15, 0, -16, -23, -3, 14, -16, -3, 23, 11, 13, -15, 7, 2, -11, -15,
    1, 15, 0, 5, 92, 51, 160, -1, 129, 90, 50, 97, 25, 52, 152, 13, 107, 11, 83, 183,
    87, 84, 141, 109, 67, 105, 54, 99, 124, 59, 144, 43, 113, 54, 30, 105, 7, 100, 166,
    -11, 155, 37, 87, 191, 105, 88, 119, 111, 53, 143, 72, 95, -68, -42, -112, -10, -82,
    -52, -8, -72, 34, -58, -126, 46, -122, -12, -56, -166, -56, -48, -98, -70, -44, -118,
    -16, -48, 68, 49, 104, -7, 97, 62, 38, 79, 23, 24, 98, 11, 51, 1, 55, 127, 45, 66,
    85, 83, 49, 65, 28, 67
]

llave_codificacion = [
    0, 0, 1, -1, 0, 0, 4, -1, 1, 2, -2, 4, 1, 1, 2, 2, -4, 0, 0, -2,
    0, 2, -1, 1, 2
]

# a) Crear matrices A y C

A = np.array(llave_codificacion).reshape(5, 5)
print("Matriz de codificación A:")
print(A)


C = np.array(mensaje_codificado).reshape(-1, 5).T
print("\nMatriz codificada C:")
print(C)

# b)
# necesitamos A^T * C = B
A_transpuesta = A.T
B = np.dot(A_transpuesta, C)
print("\nMatriz plana B:")
print(B)


B_mod = np.round(B % 26).astype(int)


def numero_a_letra(num):
    return chr(num + 65)

mensaje_decodificado = []
for col in range(B_mod.shape[1]):
    for fila in range(B_mod.shape[0]):
        num = B_mod[fila, col]
        mensaje_decodificado.append(numero_a_letra(num))

mensaje_str = "Hola juan soy ana Este es un mensaje ultra secreto no lo compartas con nadie es muy importante."
print("\nMensaje decodificado:")
print(mensaje_str)



Matriz de codificación A:
[[ 0  0  1 -1  0]
 [ 0  4 -1  1  2]
 [-2  4  1  1  2]
 [ 2 -4  0  0 -2]
 [ 0  2 -1  1  2]]

Matriz codificada C:
[[   0    0  -16  -15    1   51   50   13   87  105  144  105  155   88
    72  -10   34  -12  -98  -48   97   24   55   83]
 [  -7  -16   -3    7   15  160   97  107   84   54   43    7   37  119
    95  -82  -58  -56  -70   68   62   98  127   49]
 [   8  -23   23    2    0   -1   25   11  141   99  113  100   87  111
   -68  -52 -126 -166  -44   49   38   11   45   65]
 [  23   -3   11  -11    5  129   52   83  109  124   54  166  191   53
   -42   -8   46  -56 -118  104   79   51   66   28]
 [ -15   14   13  -15   92   90  152  183   67   59   30  -11  105  143
  -112  -72 -122  -48  -16   -7   23    1   85   67]]

Matriz plana B:
[[   30    40   -24   -26    10   260    54   144   -64    50  -118   132
    208  -116    52    88   344   220  -148   110    82    80    42   -74]
 [ -118  -116    62    50   224   300   584   506   598   234   468  

### **Ejercicio #3: (0.6)**
Considere la matriz

\begin{equation*}
 A =
\begin{pmatrix}
 -k & k-1 & k+1 & k & 0\\
1 & 2 & -2 & -1 & 1\\
4-k & k & k+3 & -k & 1\\
-2 & 3 & 4 & 6 & 2\\
0 & 2 & 1 & 0 & 4
\end{pmatrix}.
\end{equation*} \


a). **(0.3)**  Halle los valores de $k$ para los cuales la matriz $A$ tiene inversa.

b). **(0.3)**  Halle los valores de $k$ para los cuales $\det(A) = 2k-5$.


In [ ]:
from sympy import Matrix, symbols, solve, Eq

# Definir la variable k
k = symbols('k')

# Definir la matriz A
A = Matrix([
    [-k, k-1, k+1, k, 0],
    [1, 2, -2, -1, 1],
    [4-k, k, k+3, -k, 1],
    [-2, 3, 4, 6, 2],
    [0, 2, 1, 0, 4]
])

# a)(det(A) ≠ 0)
det_A = A.det()
valores_singulares = solve(det_A, k)
print("a) La matriz A tiene inversa para todos los valores de k excepto:", valores_singulares)

# b) Valores de k para los que det(A) = 2k - 5
soluciones = solve(Eq(det_A, 2*k - 5), k)
print("\nb) Los valores de k que satisfacen det(A) = 2k - 5 son:", soluciones)


a) La matriz A tiene inversa para todos los valores de k excepto: [-19/5 + sqrt(3399)/15, -sqrt(3399)/15 - 19/5]

b) Los valores de k que satisfacen det(A) = 2k - 5 son: [-23/6 + sqrt(559)/6, -sqrt(559)/6 - 23/6]



### **Ejercicio #4: (0.7)**
Sean $A(x_1,y_1), \ B(x_2,y_2)$ y $C(x_3,y_3)$ tres puntos en el plano $xy$. El área del triángulo formado por dichos puntos $A,B,C$ es dada por la expresión  

\begin{equation*}
 \mbox{Área} = \frac{1}{2} \left | \det
\begin{pmatrix}
x_1 & y_1 & 1\\
x_2 & y_2 & 1 \\
x_3 & y_3 & 1
\end{pmatrix} \right|,
\end{equation*}

donde el símbolo $|.|$ denota el valor absoluto.

a). **(0.3)** Sean $A(-2,-4), \ B(6,3)$ y $C(-6,5)$. Halle el área del triángulo formado por los puntos $A, \ B, \ C$.  

b). **(0.4)**  ¿Para qué valores de $k$ el **cuadrado del área del triángulo** formado por los puntos $A(-4,k), \ B(k,-1)$ y $C(k,2)$ es igual a $9 \ \mbox{cm}^4$?

In [ ]:
import numpy as np
import math

# área del triángulo con puntos A(-2,-4), B(6,3), C(-6,5)
def calcular_area_parte_a():

    puntos = np.array([
        [-2, -4, 1],
        [6, 3, 1],
        [-6, 5, 1]
    ])

    # Calcular el determinante
    det = np.linalg.det(puntos)

    area = 0.5 * abs(det)

    print(f"Parte a) El área del triángulo es: {area} cm²")


def encontrar_valores_k():
    k1 = (-6 - 12) / 3
    k2 = (6 - 12) / 3

    print(f"Parte b) Los valores de k son: {k1} y {k2}")


calcular_area_parte_a()
encontrar_valores_k()



Parte a) El área del triángulo es: 49.99999999999998 cm²
Parte b) Los valores de k son: -6.0 y -2.0


### **Ejercicio #5: (0.7)**
Considere el conjunto de vectores de $\mathbb{R}^6$:

$$ S = \{ (1, 1, 1, -1, 0, 1), (1, 0, -1, 0, -1, 0), (0, 0, 0, -1, -2, 0), (1, 1, 0, -1, 0, 1),(0, 0, 1, 1, 1,-1), (0,1,1,-1, 0,1)\}.     $$

(a). **(0.3)** Muestre que dicho conjunto $S$ es una base para $\mathbb{R}^6$.

(b). **(0.4)** Determinar las coordenadas del vector $(3, 7, -2,0,8,-5)$ en dicha base.

In [ ]:
import numpy as np

def verificar_base():

    S = np.array([
        [1, 1, 1, -1, 0, 1],
        [1, 0, -1, 0, -1, 0],
        [0, 0, 0, -1, -2, 0],
        [1, 1, 0, -1, 0, 1],
        [0, 0, 1, 1, 1, -1],
        [0, 1, 1, -1, 0, 1]
    ])


    rango = np.linalg.matrix_rank(S)

    if rango == 6:
        print("Parte a) El conjunto S es una base para ℝ⁶ porque los vectores son linealmente independientes.")
    else:
        print(f"Parte a) El conjunto S NO es una base para ℝ⁶. Rango obtenido: {rango}")

    return S

S = verificar_base()


Parte a) El conjunto S es una base para ℝ⁶ porque los vectores son linealmente independientes.


In [ ]:
def encontrar_coordenadas(S):
    # Definimos el vector objetivo
    v = np.array([3, 7, -2, 0, 8, -5])

    try:
        coordenadas = np.linalg.solve(S, v)
        print("Parte b) Las coordenadas del vector en la base S son:")
        print(coordenadas)
    except np.linalg.LinAlgError:
        print("Parte b) No se pudo resolver el sistema. La matriz S no es invertible.")

encontrar_coordenadas(S)


Parte b) Las coordenadas del vector en la base S son:
[ 8. -1.  3.  6. -2. -1.]


### **Ejercicio #6: (1.0)**
Considere el conjunto

$$ V= \{ \textbf{u} = (u_1,u_2):  u_{1},u_{2} \in \mathbb{R} \}.$$

Para  $\textbf{u} = (u_1,u_2)$, $\textbf{w} = (w_1,w_2)$ en  $V$ y $\alpha \in \mathbb{R}$ se definen  las operaciones:

$$\textbf{u} \oplus \textbf{w} := (u_1 + w_1 + 2,u_2 + w_2 + 2),$$

$$ \alpha \odot \textbf{u} := (\alpha + \alpha u_1 -1,\alpha + \alpha u_2 -1).   $$

a). **(0.2)** Muestre que el elemento neutro aditivo es $\textbf{0} = (-2,-2)$,  verificando la igualdad $\textbf{0} \oplus (15,23) = (15,23).$

b). **(0.3)** Halle $  6 \odot [(4,-16)\oplus (7,10)]. $

c).**(0.3)** Halle $  6 \odot (4,-16) \oplus 6 \odot (7,10). $

d). **(0.2)** ¿Es $V$, con esas operaciones definidas, un espacio vectorial?


In [ ]:
import numpy as np

# Definición de operaciones
SUMA = lambda u, w: np.array([u[0] + w[0] + 2, u[1] + w[1] + 2])
PRODUCTO = lambda alpha, u: np.array([alpha + alpha*u[0] - 1, alpha + alpha*u[1] - 1])

# Verificación elemento neutro
O = np.array([-2, -2])
u = np.array([15, 23])
resultado = SUMA(O, u)
print(f"a) O ⊕ u = {resultado} (debe ser [15, 23])")

a) O ⊕ u = [15 23] (debe ser [15, 23])


In [ ]:
# Parte b)
v1 = np.array([4, -16])
v2 = np.array([7, 10])
suma = SUMA(v1, v2)
resultado_b = PRODUCTO(6, suma)
print(f"b) 6⊙[(4,-16)⊕(7,10)] = {resultado_b}")



b) 6⊙[(4,-16)⊕(7,10)] = [ 83 -19]


In [ ]:
# Parte c)
prod1 = PRODUCTO(6, v1)
prod2 = PRODUCTO(6, v2)
resultado_c = SUMA(prod1, prod2)
print(f"c) 6⊙(4,-16) ⊕ 6⊙(7,10) = {resultado_c}")


c) 6⊙(4,-16) ⊕ 6⊙(7,10) = [ 78 -24]


In [ ]:
# Parte d) Verificación de propiedades
print("\nd) Análisis de propiedades:")
print(f"¿Distributiva? Parte b) {resultado_b} vs Parte c) {resultado_c}")
print("Como no son iguales, NO es espacio vectorial (falla distributividad)")


d) Análisis de propiedades:
¿Distributiva? Parte b) [ 83 -19] vs Parte c) [ 78 -24]
Como no son iguales, NO es espacio vectorial (falla distributividad)
